/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fatec.lista10.exercicio1;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class MainGUI extends javax.swing.JFrame {
    public Contatos contatos = new Contatos();
    Salvar salvar = new Salvar();
    Ler ler = new Ler();
    public DefaultListModel modelo = new DefaultListModel();


    
    public MainGUI() {
        initComponents();
        listaContatos.setVisibleRowCount(10);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaContatos = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        abrirAgenda = new javax.swing.JButton();
        salvarAgenda = new javax.swing.JButton();
        excluirContato = new javax.swing.JButton();
        addContact = new javax.swing.JButton();
        alterarContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 233, 244));

        jScrollPane1.setViewportView(listaContatos);

        jPanel1.setBackground(new java.awt.Color(43, 44, 40));

        abrirAgenda.setBackground(new java.awt.Color(8, 178, 227));
        abrirAgenda.setForeground(new java.awt.Color(255, 255, 255));
        abrirAgenda.setText("Carregar Agenda");
        abrirAgenda.setBorder(null);
        abrirAgenda.setMargin(new java.awt.Insets(2, 20, 2, 14));
        abrirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAgendaActionPerformed(evt);
            }
        });

        salvarAgenda.setBackground(new java.awt.Color(8, 178, 227));
        salvarAgenda.setForeground(new java.awt.Color(255, 255, 255));
        salvarAgenda.setText("Salvar Agenda");
        salvarAgenda.setBorder(null);
        salvarAgenda.setMargin(new java.awt.Insets(2, 20, 2, 14));
        salvarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAgendaActionPerformed(evt);
            }
        });

        excluirContato.setBackground(new java.awt.Color(238, 99, 82));
        excluirContato.setForeground(new java.awt.Color(255, 255, 255));
        excluirContato.setText("Excluir Contato");
        excluirContato.setBorder(null);
        excluirContato.setMargin(new java.awt.Insets(2, 20, 2, 14));
        excluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirContatoActionPerformed(evt);
            }
        });

        addContact.setBackground(new java.awt.Color(50, 222, 138));
        addContact.setForeground(new java.awt.Color(255, 255, 255));
        addContact.setText("  ADD Contato  ");
        addContact.setBorder(null);
        addContact.setMargin(new java.awt.Insets(2, 20, 2, 14));
        addContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactActionPerformed(evt);
            }
        });

        alterarContact.setBackground(new java.awt.Color(8, 178, 227));
        alterarContact.setForeground(new java.awt.Color(255, 255, 255));
        alterarContact.setText("Alterar Contato");
        alterarContact.setBorder(null);
        alterarContact.setMargin(new java.awt.Insets(2, 20, 2, 14));
        alterarContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addContact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarContact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abrirAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addContact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirContato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarContact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactActionPerformed
        String nome = JOptionPane.showInputDialog("Digite o nome: ");
        String email = JOptionPane.showInputDialog("Digite o email: ");
        String telefone = JOptionPane.showInputDialog("Digite o telefone: ");
        Pessoa pessoa = new Pessoa(nome, email, telefone);
        contatos.addPessoa(pessoa);

    }//GEN-LAST:event_addContactActionPerformed

    private void abrirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAgendaActionPerformed

    private void alterarContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarContactActionPerformed

    private void excluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirContatoActionPerformed
        String nome = JOptionPane.showInputDialog(null,"Digite o nome do contato que deseja excluir");
        
    }//GEN-LAST:event_excluirContatoActionPerformed

    private void salvarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAgendaActionPerformed
        salvar.setSalvar(contatos.getContatos());
    }//GEN-LAST:event_salvarAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAgenda;
    private javax.swing.JButton addContact;
    private javax.swing.JButton alterarContact;
    private javax.swing.JButton excluirContato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaContatos;
    private javax.swing.JButton salvarAgenda;
    // End of variables declaration//GEN-END:variables
}
